#!/bin/bash

set -euo pipefail

umask 077

label="ch.appfruit.jcds-content-cache-recovery"
program_name="$(basename "$0")"
repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
runtime_root="${HOME}/JCDS-ContentCache-runtime"
agent_directory="${HOME}/Library/LaunchAgents"
agent_path="${agent_directory}/${label}.plist"
controller_source="${repository_root}/scripts/macos-startup-controller.sh"
controller_path="${runtime_root}/bin/macos-startup-controller.sh"
controller_config="${runtime_root}/startup-controller.conf"
agent_source="${repository_root}/deploy/macos-production/${label}.plist"
health_url="https://jcds-cache.appfruit.ch:8443/health/ready"
ca_file=""
with_monitoring="false"
docker_ready_timeout=300
container_ready_timeout=300
https_ready_timeout=120
poll_interval=5

usage() {
  cat <<EOF
Usage:
  ${program_name} install [options]
  ${program_name} status
  ${program_name} reconcile
  ${program_name} uninstall

Install options:
  --health-url HTTPS_URL             Default: ${health_url}
  --with-monitoring                  Include compose.monitoring.yaml.
  --ca-file PATH                     Explicit CA bundle for readiness checks.
  --docker-ready-timeout SECONDS     Default: ${docker_ready_timeout}.
  --container-ready-timeout SECONDS  Default: ${container_ready_timeout}.
  --https-ready-timeout SECONDS      Default: ${https_ready_timeout}.
  --poll-interval SECONDS            Default: ${poll_interval}.

The production runtime path is intentionally fixed at:
  ${runtime_root}
EOF
}

fail() {
  printf '%s: %s\n' "${program_name}" "$1" >&2
  exit 1
}

[[ $# -ge 1 ]] || {
  usage >&2
  exit 64
}

action="$1"
shift

if [[ "${action}" != "install" && $# -gt 0 ]]; then
  fail "${action} does not accept options"
fi

while (( $# > 0 )); do
  case "$1" in
    --health-url)
      (( $# >= 2 )) || fail "--health-url requires a URL"
      health_url="$2"
      shift 2
      ;;
    --with-monitoring)
      with_monitoring="true"
      shift
      ;;
    --ca-file)
      (( $# >= 2 )) || fail "--ca-file requires a path"
      ca_file="$2"
      shift 2
      ;;
    --docker-ready-timeout)
      (( $# >= 2 )) || fail "--docker-ready-timeout requires seconds"
      docker_ready_timeout="$2"
      shift 2
      ;;
    --container-ready-timeout)
      (( $# >= 2 )) || fail "--container-ready-timeout requires seconds"
      container_ready_timeout="$2"
      shift 2
      ;;
    --https-ready-timeout)
      (( $# >= 2 )) || fail "--https-ready-timeout requires seconds"
      https_ready_timeout="$2"
      shift 2
      ;;
    --poll-interval)
      (( $# >= 2 )) || fail "--poll-interval requires seconds"
      poll_interval="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

[[ "$(uname -s)" == "Darwin" ]] || fail "this management command must run on macOS"
(( EUID != 0 )) || fail "run this command as the dedicated service account, not as root"

uid="$(id -u)"
domain="gui/${uid}"
service_target="${domain}/${label}"

case "${action}" in
  install)
    [[ -x "${controller_source}" ]] || fail "startup controller is missing or not executable"
    [[ -f "${agent_source}" ]] || fail "LaunchAgent definition is missing"
    [[ -f "${runtime_root}/deployment.production.env" ]] \
      || fail "${runtime_root}/deployment.production.env is missing"
    [[ -d /Applications/Docker.app ]] || fail "/Applications/Docker.app is missing"
    launchctl print "${domain}" >/dev/null 2>&1 \
      || fail "the dedicated user's GUI launchd domain is unavailable"

    mkdir -p "${runtime_root}/bin" "${runtime_root}/logs" "${agent_directory}"
    chmod 0700 "${runtime_root}" "${runtime_root}/bin" "${runtime_root}/logs"
    chmod 0600 "${runtime_root}/deployment.production.env"

    base_compose_sha256="$(/usr/bin/shasum -a 256 \
      "${repository_root}/deploy/macos-production/compose.yaml" | /usr/bin/awk '{print $1}')"
    monitoring_compose_sha256="$(/usr/bin/shasum -a 256 \
      "${repository_root}/deploy/macos-production/compose.monitoring.yaml" | /usr/bin/awk '{print $1}')"

    temporary_config="$(mktemp "${runtime_root}/.startup-controller.conf.XXXXXX")"
    trap 'rm -f -- "${temporary_config:-}"' EXIT
    {
      printf '# Generated by %s; contains no credentials.\n' "${program_name}"
      printf 'repository_root=%s\n' "${repository_root}"
      printf 'health_url=%s\n' "${health_url}"
      printf 'ca_file=%s\n' "${ca_file}"
      printf 'with_monitoring=%s\n' "${with_monitoring}"
      printf 'docker_ready_timeout=%s\n' "${docker_ready_timeout}"
      printf 'container_ready_timeout=%s\n' "${container_ready_timeout}"
      printf 'https_ready_timeout=%s\n' "${https_ready_timeout}"
      printf 'poll_interval=%s\n' "${poll_interval}"
      printf 'base_compose_sha256=%s\n' "${base_compose_sha256}"
      printf 'monitoring_compose_sha256=%s\n' "${monitoring_compose_sha256}"
    } >"${temporary_config}"
    chmod 0600 "${temporary_config}"

    /usr/bin/plutil -lint "${agent_source}" >/dev/null
    "${controller_source}" --config "${temporary_config}" --validate-only

    launchctl bootout "${service_target}" >/dev/null 2>&1 || true
    /usr/bin/install -m 0700 "${controller_source}" "${controller_path}"
    mv -f "${temporary_config}" "${controller_config}"
    chmod 0600 "${controller_config}"
    /usr/bin/install -m 0644 "${agent_source}" "${agent_path}"
    launchctl bootstrap "${domain}" "${agent_path}"
    launchctl enable "${service_target}"
    launchctl kickstart -k "${service_target}"

    trap - EXIT
    printf 'Installed and started %s for user %s.\n' "${label}" "$(id -un)"
    printf 'Latest result: %s/startup-recovery.status\n' "${runtime_root}"
    ;;
  status)
    (( $# == 0 )) || fail "status does not accept options"
    launchctl print "${service_target}"
    if [[ -f "${runtime_root}/startup-recovery.status" ]]; then
      printf '\nLatest controller result:\n'
      /bin/cat "${runtime_root}/startup-recovery.status"
    fi
    ;;
  reconcile)
    (( $# == 0 )) || fail "reconcile does not accept options"
    [[ -f "${agent_path}" ]] || fail "LaunchAgent is not installed"
    launchctl kickstart -k "${service_target}"
    printf 'Reconciliation requested for %s.\n' "${label}"
    ;;
  uninstall)
    (( $# == 0 )) || fail "uninstall does not accept options"
    launchctl bootout "${service_target}" >/dev/null 2>&1 || true
    rm -f -- "${agent_path}" "${controller_path}" "${controller_config}"
    printf 'Removed %s. Runtime environment, TLS files, logs and Docker volumes were preserved.\n' "${label}"
    ;;
  *)
    usage >&2
    exit 64
    ;;
esac
